version: "3.7"
services:
  expose:
    image: ghcr.io/wartner-io/expose-docker:main
    ports:
      - 8080:${PORT}
     extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      port: ${PORT}
      domain: ${DOMAIN}
      username: ${ADMIN_USERNAME}
      password: ${ADMIN_PASSWORD}
    restart: always
    volumes:
      - ./database/expose.db:/root/.expose
